In [236]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [237]:
vdef = pd.read_csv("VariableDefinitions.csv")

In [238]:
ssub = pd.read_csv("SampleSubmission.csv")

In [239]:
test = pd.read_csv("Test.csv")

In [240]:
train = pd.read_csv("Train.csv")

In [241]:
from sklearn import metrics
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, f1_score
from sklearn.preprocessing import LabelEncoder, LabelBinarizer
from sklearn.model_selection import train_test_split

In [242]:
le = LabelEncoder()
lb = LabelBinarizer()

In [243]:
train.shape

(23524, 13)

In [244]:
test.shape

(10086, 12)

In [245]:
train["country"] = le.fit_transform(train["country"])

In [246]:
test["country"] = le.fit_transform(test["country"])

In [247]:
test["location_type"] = test["location_type"].apply(lambda x:1 if x== "Rural" else 0)

In [248]:
train["bank_account"] = train["bank_account"].replace({"Yes" : 1, "No" : 0})

In [249]:
train["location_type"] = train["location_type"].apply(lambda x:1 if x== "Rural" else 0)

In [250]:
train["cellphone_access"] = train["cellphone_access"].replace({"Yes" : 1, "No" : 0})

In [251]:
test["cellphone_access"] = test["cellphone_access"].replace({"Yes" : 1, "No" : 0})

In [252]:
train.drop("uniqueid", axis = "columns", inplace = True )

In [253]:
test["gender_of_respondent"] = test["gender_of_respondent"].replace({"Male" : 1, "Female" : 0})

In [254]:
train["gender_of_respondent"] = train["gender_of_respondent"].replace({"Male" : 1, "Female" : 0})

In [255]:
test["relationship_with_head"] = le.fit_transform(test["relationship_with_head"])

In [256]:
train["relationship_with_head"] = le.fit_transform(train["relationship_with_head"])

In [257]:
test["marital_status"] = le.fit_transform(test["marital_status"])

In [258]:
train["marital_status"] = le.fit_transform(train["marital_status"])

In [259]:
test["education_level"] = le.fit_transform(test["education_level"])

In [260]:
train["education_level"] = le.fit_transform(train["education_level"])

In [261]:
test["job_type"] = le.fit_transform(test["job_type"])

In [262]:
train["job_type"] = le.fit_transform(train["job_type"])

In [263]:
test["uniqueid"] = le.fit_transform(test["uniqueid"])

In [264]:
X = train.drop("bank_account", axis = "columns")

In [265]:
test.drop("uniqueid", axis = "columns", inplace = True )

In [266]:
y

0        1
1        0
2        1
3        0
4        0
        ..
23519    0
23520    0
23521    0
23522    0
23523    0
Name: bank_account, Length: 23524, dtype: int64

In [267]:
y = train["bank_account"]

In [268]:
rfc = RandomForestClassifier()

In [269]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1234)

In [270]:
rfc.fit(X_train, y_train)

RandomForestClassifier()

In [271]:
rfc.predict(X_test)

array([1, 0, 0, ..., 0, 0, 0], dtype=int64)

In [272]:
rfcpredict = rfc.predict(X_test)

In [273]:
rfc.predict(test)

array([1, 1, 0, ..., 0, 0, 0], dtype=int64)

In [274]:
accuracy_score(y_test, rfcpredict) * 100

86.50371944739639

In [275]:
f1_score(y_test, rfcpredict)

0.4168962350780533

In [277]:
gnb = GaussianNB()

In [279]:
gnb.fit(X_train, y_train)

GaussianNB()

In [280]:
gnb.predict(X_test)

array([1, 0, 0, ..., 0, 0, 0], dtype=int64)

In [281]:
gnb.predict(test)

array([1, 1, 0, ..., 1, 0, 0], dtype=int64)

In [284]:
gnbpredict = gnb.predict(X_test)

In [285]:
accuracy_score(y_test, gnbpredict) * 100

82.8480340063762

In [286]:
f1_score(y_test, gnbpredict)

0.45509790681971646

In [287]:
lrg = LogisticRegression()

In [288]:
lrg.fit(X_train, y_train)

C:\Users\HP\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [289]:
lrg.predict(X_test)

array([1, 0, 0, ..., 0, 0, 0], dtype=int64)

In [290]:
lrg.predict(test)

array([0, 1, 0, ..., 0, 0, 0], dtype=int64)

In [294]:
lrgtest = lrg.predict(test)

In [291]:
lrgpredict = lrg.predict(X_test)

In [292]:
accuracy_score(y_test, lrgpredict) * 100

87.03506907545164

In [293]:
f1_score(y_test, lrgpredict)

0.29723502304147464

In [296]:
p = pd.read_csv("Test.csv")

In [304]:
a = pd.DataFrame({"uniqueid":p["uniqueid"] + " x " + p["country"], "bank_account":lrgtest})

In [305]:
a

uniqueid  bank_account
0       uniqueid_6056 x Kenya             0
1       uniqueid_6060 x Kenya             1
2       uniqueid_6065 x Kenya             0
3       uniqueid_6072 x Kenya             0
4       uniqueid_6073 x Kenya             0
...                       ...           ...
10081  uniqueid_2998 x Uganda             0
10082  uniqueid_2999 x Uganda             0
10083  uniqueid_3000 x Uganda             0
10084  uniqueid_3001 x Uganda             0
10085  uniqueid_3002 x Uganda             0

[10086 rows x 2 columns]

In [306]:
Hackathon = a

In [307]:
Hackathon.to_csv("Hackathon1.csv", index = False)

In [308]:
Hackathon.head()

uniqueid  bank_account
0  uniqueid_6056 x Kenya             0
1  uniqueid_6060 x Kenya             1
2  uniqueid_6065 x Kenya             0
3  uniqueid_6072 x Kenya             0
4  uniqueid_6073 x Kenya             0